from tortoise import migrations
from tortoise.migrations import operations as ops

# id -> (obecna nazwa techniczna, nazwa na stronie)
NAMES: dict[int, tuple[str, str]] = {
    1: ("czekolada-mleczna-malina", "Mleczna czekolada z maliną"),
    2: ("yerba-mate-wild-power-cannabis", "Yerba Wild Power Cannabis"),
    3: ("canabis-opakowanie", "Yerba Cannabis w opakowaniu"),
    4: ("syrop-cynamonowy", "Syrop cynamonowy"),
    5: ("syrop-cytrynowy", "Syrop cytrynowy"),
    6: ("syrop-imbirowy", "Syrop imbirowy"),
    7: ("syrop-karmelowy", "Syrop karmelowy"),
    8: ("chillout", "Yerba Wild Power Chillout"),
    9: ("czekolada-ekwador-80-ksylitol", "Czekolada Ekwador 80% z ksylitolem"),
    10: ("czekolada-madagaskar-46", "Czekolada Madagaskar 46%"),
    11: ("czekolada-mleczna-piwo", "Mleczna czekolada z piwem"),
    12: ("yerba-mate-wild-power-zestaw", "Zestaw yerba Wild Power"),
    13: ("syrop-mietowy", "Syrop miętowy"),
    14: ("syrop-migdalowy", "Syrop migdałowy"),
    15: ("czekoladka-gorzka-milego-dnia", "Gorzka czekoladka „Miłego dnia”"),
    16: ("czekolada-ciemna-malina-jablko", "Ciemna czekolada z maliną i jabłkiem"),
    17: ("czekolada-biala-zurawina-pistacje", "Biała czekolada z żurawiną i pistacjami"),
    18: ("czekolada-mleczna-truskawka", "Mleczna czekolada z truskawką"),
    19: ("czekolada-mleczna-jablko-wisnia", "Mleczna czekolada z jabłkiem i wiśnią"),
    20: ("czekolada-mleczna-mango-marakuja", "Mleczna czekolada z mango i marakują"),
    21: ("czekoladka-mleczna-milego-dnia", "Mleczna czekoladka „Miłego dnia”"),
    22: ("syrop-pomaranczowy", "Syrop pomarańczowy"),
    23: ("syrop-rozany", "Syrop różany"),
    24: ("syrop-waniliowy", "Syrop waniliowy"),
    25: ("after-winter 1920x1920 EC", "After Winter"),
    26: ("kawa-osm-sernika 1920x1920-ec", "Kawa sernikowa"),
    27: ("kawa-biala-czeko-malina", "Kawa z białą czekoladą i maliną"),
    28: ("Energia Poludnia [1]", "Energia południa"),
    29: ("matero czarne", "Matero czarne"),
    30: ("matero-czerwone", "Matero czerwone"),
    31: ("matero-stal-czarne", "Matero stalowe czarne"),
    32: ("bombilla", "Bombilla"),
    33: ("szczoteczka", "Szczoteczka do bombilli"),
    34: ("syrop-mniszek-pokrzywa", "Syrop z mniszka i pokrzywy"),
    35: ("syrop-sosna", "Syrop sosnowy"),
    36: ("syrop-ostropest", "Syrop z ostropestu"),
    37: ("migdal-w-mlecznej-czekoladzie", "Migdał w mlecznej czekoladzie"),
    38: ("malina-w-ciemnej-czekoladzie", "Malina w ciemnej czekoladzie"),
    39: ("nerkowiec-w-mlecznej-czekoladzie", "Nerkowiec w mlecznej czekoladzie"),
    40: ("migdal-w-bialej-czekoladzie", "Migdał w białej czekoladzie"),
    41: ("goraca-czekolada", "Gorąca czekolada"),
    42: ("matero miodowe", "Matero miodowe"),
    43: ("bombilla bambusowa", "Bombilla bambusowa"),
    44: ("liza", "Bombilla Liza"),
    45: ("bombilla-liza-ze-szczoteczka-srebrna", "Bombilla Liza ze szczoteczką"),
    46: ("matero-drive", "Matero Drive"),
    47: ("matero brazowe", "Matero brązowe"),
    48: ("matero-bialy", "Matero białe"),
    49: ("truskawka-w-mlecznej-czekoladzie", "Truskawka w mlecznej czekoladzie"),
    50: ("migdal-w-slonym-karmelu", "Migdał w słonym karmelu"),
    51: ("matero-paski-zolte", "Matero w żółte paski"),
    52: ("syrop-malinowy", "Syrop malinowy"),
    53: ("syrop-malinowy-z-lipa", "Syrop malinowy z lipą"),
    54: ("syrop-zurawinowy", "Syrop żurawinowy"),
    55: ("syrop-z-kwiatow-czarnego-bzu", "Syrop z kwiatów czarnego bzu"),
    56: ("bombilla-lyzeczka", "Bombilla łyżeczka"),
    57: ("bombilla-spiralka", "Bombilla spiralka"),
    58: ("kombucha OAK EDELFLOWER 800x800 xl", "Kombucha z bzem"),
    59: ("kombucha oak white grapes 800x800 XL", "Kombucha białe winogrona"),
    60: ("kombucha oak chocolate 800X800-XL", "Kombucha czekoladowa"),
    61: ("deguarana-opakowanie", "Yerba De Guarana w opakowaniu"),
    62: ("yoga-opakowanie", "Yerba Yoga w opakowaniu"),
    63: ("iq", "Yerba Wild Power IQ"),
    64: ("Mate Brazil Despalada", "Yerba Brazil Despalada"),
    65: ("lemon-opakowanie", "Yerba Lemon w opakowaniu"),
    66: ("fitness-opakowania", "Yerba Fitness w opakowaniu"),
    67: ("wild-energy-opakowanie", "Yerba Wild Energy w opakowaniu"),
    68: ("very-berry", "Yerba Wild Power Very Berry"),
    69: ("diament-braz", "Matero Diament brązowe"),
    70: ("matero-diament-bialy", "Matero Diament białe"),
    71: ("matero-diament-czarny", "Matero Diament czarne"),
    72: ("ziarno-kawy-w-mlecznej-czekoladzie", "Ziarno kawy w mlecznej czekoladzie"),
    73: ("orzech-laskowy-w-mlecznej-czekoladzie", "Orzech laskowy w mlecznej czekoladzie"),
    74: ("ciasteczka-korzenne-w-czekoladzie", "Ciasteczka korzenne w czekoladzie"),
    75: ("yerba-mate-wild-power-cannabis-zestaw", "Zestaw yerba Cannabis"),
    76: ("yerba-mate-wild-power-very-berry-zestaw", "Zestaw yerba Very Berry"),
    77: ("yerba-mate-wild-power-lemon-zestaw", "Zestaw yerba Lemon"),
    78: ("mate-cherry-opakowanie", "Yerba wiśniowa w opakowaniu"),
    79: ("yerba-mate-wild-power-wild-energy-zestaw", "Zestaw yerba Wild Energy"),
    80: ("Bombilla Sortija", "Bombilla Sortija"),
    81: ("syrop-wisniowy-z-rumem", "Syrop wiśniowy z rumem"),
    82: ("argentina", "Yerba Wild Power Argentina"),
    83: ("goraca-czekolada-swiateczna", "Gorąca czekolada świąteczna"),
    84: ("yerbomos-zielony", "Yerbomos zielony"),
    85: ("syrop-slony-karmel", "Syrop słony karmel"),
    86: ("syrop-miodowy-cytryna-imbir", "Syrop miodowy z cytryną i imbirem"),
    87: ("mint", "Yerba Wild Power Mint"),
    88: ("chillout", "Yerba Wild Power Chillout"),
    89: ("yerba-mate-wild-power-argentina", "Yerba Wild Power Argentina"),
    90: ("yerba-mate-wild-power-brazil", "Yerba Wild Power Brazil"),
    91: ("chillout", "Yerba Wild Power Chillout"),
    92: ("yerba-mate-wild-power-crazy-cherry", "Yerba Wild Power Crazy Cherry"),
    93: ("yerba-mate-wild-power-de-guarana", "Yerba Wild Power De Guarana"),
    94: ("yerba-mate-wild-power-fitness", "Yerba Wild Power Fitness"),
    95: ("yerba-mate-wild-power-iq", "Yerba Wild Power IQ"),
    96: ("yerba-mate-wild-power-lemon", "Yerba Wild Power Lemon"),
    97: ("yerba-mate-wild-power-mint", "Yerba Wild Power Mint"),
    98: ("yerba-mate-wild-power-very-berry", "Yerba Wild Power Very Berry"),
    99: ("yerba-mate-wild-power-wild-energy", "Yerba Wild Power Wild Energy"),
    100: ("yerba-mate-wild-power-yoga", "Yerba Wild Power Yoga"),
    101: ("Kubek beczulka Rafa koralowa [1920x1920]", "Kubek beczułka Rafa koralowa"),
    102: ("Kubek beczulka Bratki [1920x1920]", "Kubek beczułka Bratki"),
    103: ("Kubek beczulka Motyl Kwiaty polne [1920x1920]", "Kubek beczułka Motyl"),
    104: ("CARMANI-KUBKI-MAKI-1920X1920", "Kubek Carmani Maki"),
    105: ("CARMANI-MAKI-1920X1920", "Filiżanka Carmani Maki"),
    106: ("Filizanka espresso Irysy [1920x1920]", "Filiżanka espresso Irysy"),
    107: ("Filizanka espresso Taras kawiarni noca [1920x1920]", "Filiżanka espresso Taras kawiarni nocą"),
    108: ("Kubek z zaparzaczem kulka Pocalunek [1920x1920]", "Kubek Pocałunek z zaparzaczem"),
    109: ("Kubek 650ml Pocalunek [1920x1920]", "Kubek Pocałunek 650 ml"),
    110: ("Kubek z sitkiem beczulka Pocalunek [1920x1920]", "Kubek beczułka Pocałunek"),
    111: ("CARMANI-KUBKI-BZY-1920x1920", "Kubek Carmani Bez"),
    112: ("CARMANI-POLNE-KWIATY-1920x1920", "Kubek Carmani Polne kwiaty"),
    113: ("CARMANI-KOLIBER-1920X1920", "Kubek Carmani Koliber"),
    114: ("skrzynka srebrna", "Skrzynka srebrna"),
    115: ("skrzynka zielen-morska", "Skrzynka zieleń morska"),
    116: ("Frenchpress 0,35l", "French press 0,35 l"),
    117: ("Frenchpress 0,6l", "French press 0,6 l"),
    118: ("Frenchpress 0,8", "French press 0,8 l"),
    119: ("Frenchpress 1l", "French press 1 l"),
    120: ("AFRICAN QUEEN", "African Queen"),
    121: ("AKSAMITNY POCALUNEK", "Aksamitny pocałunek"),
    122: ("ALEJA GWIAZD", "Aleja gwiazd"),
    123: ("ASSAM DEKORAI", "Assam Dekorai"),
    124: ("ASSAM DIKOM STGFOPI", "Assam Dikom"),
    125: ("ASSAM SATRUPA", "Assam Satrupa"),
    126: ("BANCHA", "Bancha"),
    127: ("BI LUO CHUN", "Bi Luo Chun"),
    128: ("BLUE-BUTTERFLY", "Blue Butterfly"),
    129: ("bombilla j-m-perez", "Bombilla J.M. Perez"),
    130: ("CASABLANKA", "Casablanca"),
    131: ("CEYLON DIMBULA OPA2", "Ceylon Dimbula"),
    132: ("CEYLON HIGH GROWN OP", "Ceylon High Grown"),
    133: ("CHINA-PAI-MU-TAN", "Pai Mu Tan"),
    134: ("china golden yunnan", "China Golden Yunnan"),
    135: ("CHINA GREEN YUNNAN", "China Green Yunnan"),
    136: ("CHINA GUNPOWDER", "China Gunpowder"),
    137: ("CHINA GUNPOWDER-SUPER", "China Gunpowder Super"),
    138: ("chwila przy kominku", "Chwila przy kominku"),
    139: ("ciemna z bananem i malina", "Ciemna czekolada z bananem i maliną"),
    140: ("ciemna ze sliwka i kardamonem", "Ciemna czekolada ze śliwką i kardamonem"),
    141: ("CYTRYNA Z IMBIREM", "Cytryna z imbirem"),
    142: ("CYTRYNKI Z WHISKY", "Cytrynki z whisky"),
    143: ("CYTRYNKI Z ZURAWINA I CYNAMONEM", "Cytrynki z żurawiną i cynamonem"),
    144: ("CZARNY BEZ Z SOKIEM CYTRYNOWYM", "Czarny bez z sokiem cytrynowym"),
    145: ("CZEKOLADA-CIEMNA", "Ciemna czekolada"),
    146: ("CZEKOLADA-CIEMNA-Z-WISNIA", "Ciemna czekolada z wiśnią"),
    147: ("CZEKOLADA-MLECZNA-Z-CAPPUCINO", "Mleczna czekolada z cappuccino"),
    148: ("CZEKOLADA-ZIEMNA-Z-POMARANCZA", "Czekolada z pomarańczą"),
    149: ("CZEKOLADA CIEMNA Z POMARANCZA I CYNAMONEM", "Ciemna czekolada z pomarańczą i cynamonem"),
    150: ("CZEKOLADOWA-LAGUNA", "Czekoladowa laguna"),
    151: ("DA HONG PAO", "Da Hong Pao"),
    152: ("DA HONG PAO STD", "Da Hong Pao standard"),
    153: ("DARJEELING FIRST FLUSH", "Darjeeling First Flush"),
    154: ("DARJEELING SF", "Darjeeling Second Flush"),
    155: ("EARL-GREY-LAWENDOWY", "Earl Grey z lawendą"),
    156: ("EARL-GREY-niebieski-kwiat", "Earl Grey z niebieskim kwiatem"),
    157: ("EARL-GREY-YELLOW", "Earl Grey Yellow"),
    158: ("EARL GREY", "Earl Grey"),
    159: ("EARL GREY - FANTASY", "Earl Grey Fantasy"),
    160: ("EARL GREY - LEMON", "Earl Grey Lemon"),
    161: ("EARL GREY - MADAM GREY", "Earl Grey Madam Grey"),
    162: ("EARL GREY - ROYAL", "Earl Grey Royal"),
    163: ("EARL GREY - ROZANY", "Earl Grey różany"),
    164: ("EARL GREY - SPICY", "Earl Grey Spicy"),
    165: ("EARL GREY - WECHIKUL CZASU", "Earl Grey Wehikuł czasu"),
    166: ("EARL GREY - YELLOW", "Earl Grey Yellow"),
    167: ("EARL GREY -SERCE MATKI", "Earl Grey Serce matki"),
    168: ("ENGLISH BREAKFAST", "English Breakfast"),
    169: ("GEN MAI CHA", "Genmaicha"),
    170: ("GOLDEN YUNNAN", "Golden Yunnan"),
    171: ("GUNPOWDER SUPER BLACK", "Gunpowder Super Black"),
    172: ("gyokuro", "Gyokuro"),
    173: ("HISZPANSKA-MANDARYNKA", "Hiszpańska mandarynka"),
    174: ("ICE TEA-BRZOSKWINIOWA-RUMBA", "Ice tea brzoskwiniowa rumba"),
    175: ("ICE TEA CYTRYNOWA", "Ice tea cytrynowa"),
    176: ("ICE TEA MANGO TWIST", "Ice tea Mango Twist"),
    177: ("imbir z sokiem cytrynowwym", "Imbir z sokiem cytrynowym"),
    178: ("IMBIR Z SOKIEM CYTRYNOWYM", "Imbir z sokiem cytrynowym"),
    179: ("IMIE-ROZY", "Imię róży"),
    180: ("JAPAN-ARASHIYAMA", "Arashiyama"),
    181: ("JAPAN SENCHA FUKUJYU", "Sencha Fukujyu"),
    182: ("JAPAN SENCHA GYOKURO", "Sencha Gyokuro"),
    183: ("japan sencha kagoshima", "Sencha Kagoshima"),
    184: ("JAPAN SENCHA MIYAZAKI", "Sencha Miyazaki"),
    185: ("JAPAN SENCHA UCHIYAMA", "Sencha Uchiyama"),
    186: ("japan tamaryokucha", "Tamaryokucha"),
    187: ("JASMINE OOLONG", "Oolong jaśminowy"),
    188: ("jun chiyabari black", "Jun Chiyabari"),
    189: ("KENYA TINDERET", "Kenya Tinderet"),
    190: ("KING-OF-EARLGREY", "King of Earl Grey"),
    191: ("KONFITURA-Z-DZIKIEJ-ROZY", "Konfitura z dzikiej róży"),
    192: ("KOREA JEJU OP", "Korea Jeju"),
    193: ("KSIAZE PERSJI", "Książę Persji"),
    194: ("KWIAT-MILOSCI", "Kwiat miłości"),
    195: ("KWIAT GRANATU", "Kwiat granatu"),
    196: ("LAPSANG-SOUCHONG", "Lapsang Souchong"),
    197: ("LAZY-DAY", "Lazy Day"),
    198: ("LEMONIADA RABARBAROWA", "Lemoniada rabarbarowa"),
    199: ("LIMONKI", "Limonki"),
    200: ("long zu jasminowa", "Long Zu jaśminowa"),
    201: ("long zu white", "Long Zu biała"),
    202: ("MADAGASKAR", "Madagaskar"),
    203: ("MAILNA Z SOKIEM CYTRYNOWYM", "Malina z sokiem cytrynowym"),
    204: ("MALINOWA", "Malinowa"),
    205: ("MALINOWA-CHMURKA", "Malinowa chmurka"),
    206: ("maliny-z sokiem cytrynowym", "Maliny z sokiem cytrynowym"),
    207: ("MALINY W SYROPIE", "Maliny w syropie"),
    208: ("MAMMA MIA", "Mamma Mia"),
    209: ("MATECZNIK-MIOD-KROLEWSKI", "Miód królewski"),
    210: ("MATECZNIK-MIOD SEZONOWY", "Miód sezonowy"),
    211: ("MATECZNIK-PIGWOWIEC-W-SYROPIE", "Pigwowiec w syropie"),
    212: ("MILK-OOLONG", "Milk Oolong"),
    213: ("miod-z-malinowa-rapsodia", "Miód Malinowa Rapsodia"),
    214: ("miod akacjowy-z malinowa rapsodia", "Miód akacjowy Malinowa Rapsodia"),
    215: ("miod akacjowy z migdalami", "Miód akacjowy z migdałami"),
    216: ("miod akacjowy z orzechami laskowymi", "Miód akacjowy z orzechami laskowymi"),
    217: ("MIOD LIPOWY", "Miód lipowy"),
    218: ("MIOD Z MIETA", "Miód z miętą"),
    219: ("MIODOWA ROZA", "Miód różany"),
    220: ("MIODOWY-CYNAMON", "Miód z cynamonem"),
    221: ("miodowy-imbir", "Miód z imbirem"),
    222: ("mus malinowy", "Mus malinowy"),
    223: ("NEPAL-GOLDEN-BLACK", "Nepal Golden Black"),
    224: ("OCEAN-WSPOMNIEN", "Ocean wspomnień"),
    225: ("OOLONG", "Oolong"),
    226: ("oolong tung ting cinnamon", "Oolong Tung Ting z cynamonem"),
    227: ("OOLONG WONDER GOPALDHARA", "Oolong Wonder Gopaldhara"),
    228: ("ORANGE-DREAM", "Orange Dream"),
    229: ("ORIENTALNA PRZYGODA", "Orientalna przygoda"),
    230: ("OWOCOWY-ZMIERZCH", "Owocowy zmierzch"),
    231: ("PELNIA-SZCZESCIA", "Pełnia szczęścia"),
    232: ("PIECZONE JABLUSZKO", "Pieczone jabłuszko"),
    233: ("PIGWA", "Pigwa"),
    234: ("PIKANTNA DYNIA", "Pikantna dynia"),
    235: ("PLATKI-ROZY", "Płatki róży"),
    236: ("POEZJA SMAKU", "Poezja smaku"),
    237: ("PU ERH", "Pu-erh"),
    238: ("PU ERH FITNESS", "Pu-erh Fitness"),
    239: ("PU ERH MALAKKA", "Pu-erh Malakka"),
    240: ("PU ERH SUPERIOR", "Pu-erh Superior"),
    241: ("PUEHR ROYAL PALACE", "Pu-erh Royal Palace"),
    242: ("PUERH WISNIOWO-RUMOWY", "Pu-erh wiśniowo-rumowy"),
    243: ("PYCHOTKA", "Pychotka"),
    244: ("ruby z zurawina", "Ruby z żurawiną"),
    245: ("rzemieslnicza-migdal", "Rzemieślnicza czekolada z migdałami"),
    246: ("SENCHA", "Sencha"),
    247: ("sencha black", "Sencha Black"),
    248: ("SENCHA JAPAN STYLE", "Sencha Japan Style"),
    249: ("silver needle", "Silver Needle"),
    250: ("sliwka z orzechami i cynamonem", "Śliwka z orzechami i cynamonem"),
    251: ("SLODKA POKUSA", "Słodka pokusa"),
    252: ("SNIADANIE U TIFFANYEGO", "Śniadanie u Tiffany'ego"),
    253: ("SPACER-KOCHANKOW", "Spacer kochanków"),
    254: ("SUNON YELLOW TEA", "Sunon"),
    255: ("SUNRISE", "Sunrise"),
    256: ("SYROP-ARONIA-CZARNY-BEZ", "Syrop z aronii i czarnego bzu"),
    257: ("TAJEMNICA-INKOW", "Tajemnica Inków"),
    258: ("TROPIKALNA-POKUSA", "Tropikalna pokusa"),
    259: ("TRUSKAWKI ZE SMIETANA", "Truskawki ze śmietaną"),
    260: ("TURECKA BOP", "Turecka herbata"),
    261: ("WHITE-ICE-TEA", "White Ice Tea"),
    262: ("WHITE-ROSE", "White Rose"),
    263: ("white moon", "White Moon"),
    264: ("WINOGRONOWE-MUSCATO", "Winogronowe Moscato"),
    265: ("WIOSENNY-SPACER", "Wiosenny spacer"),
    266: ("WISNIA-Z-KARDAMONEM", "Wiśnia z kardamonem"),
    267: ("WISNIE W RUMIE", "Wiśnie w rumie"),
    268: ("YELLOW-BUDS", "Yellow Buds"),
    269: ("YERBA-DODATKOWE-1-600X600", "Yerba mate"),
    270: ("YUN MING CZARNY", "Yun Ming czarna"),
    271: ("YUN MING ZIELONY", "Yun Ming zielona"),
    272: ("YUNNAN BLACK PREMIUM", "Yunnan Black Premium"),
    273: ("ZLOTA GRUSZKA", "Złota gruszka"),
    274: ("ZLOTE-WSPOMNIENIE", "Złote wspomnienie"),
    275: ("ZMYSLOWE-MANGO", "Zmysłowe mango"),
}


async def _apply(client, column: int) -> None:
    for item_id, names in NAMES.items():
        await client.execute_query(
            "UPDATE items SET name = $1 WHERE id = $2 AND name = $3",
            [names[column], item_id, names[1 - column]],
        )


async def rename_items(apps, schema_editor) -> None:
    await _apply(schema_editor.client, 1)


async def restore_items(apps, schema_editor) -> None:
    await _apply(schema_editor.client, 0)


class Migration(migrations.Migration):
    dependencies = [("models", "0006_additives_category")]
    initial = False
    operations = [
        ops.RunPython(rename_items, restore_items),
    ]
